In [1]:
import numpy as np

### Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
a[2]

np.int64(3)

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0., 100., 12)

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

### Multi-dimensional arrays

In [10]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [12]:
n[1, 1]

np.int64(5)

In [13]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [14]:
n[2]

array([7, 8, 9])

In [15]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [16]:
n[:, 1]

array([20,  5,  1])

In [17]:
n[:, 2]

array([3, 6, 1])

In [18]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Random arrays

In [19]:
np.random.rand(5, 2)

array([[0.90144207, 0.13085874],
       [0.4225728 , 0.27743389],
       [0.64619384, 0.32424169],
       [0.2051479 , 0.66000066],
       [0.85569056, 0.25004836]])

In [20]:
100 * np.random.rand(5, 2)

array([[58.97979587,  2.30362576],
       [97.01100314, 28.40789856],
       [95.98973532,  0.65596557],
       [51.36637969, 26.25115927],
       [12.16576284, 82.25123294]])

In [34]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [42]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [50]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [52]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [53]:
a + 1

array([1, 2, 3, 4, 5])

In [54]:
a * 2

array([0, 2, 4, 6, 8])

In [57]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [58]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparison operations

In [61]:
a > 2

array([False, False, False,  True,  True])

In [62]:
a > b

array([False, False,  True,  True,  True])

In [64]:
# by condition filter
a[a > b]

array([2, 3, 4])

### Summarise operations

In [66]:
a

array([0, 1, 2, 3, 4])

In [68]:
a.min()

np.int64(0)

In [69]:
a.max()

np.int64(4)

In [71]:
a.sum()

np.int64(10)

In [72]:
a.mean()

np.float64(2.0)

In [73]:
# standard deviation
a.std()

np.float64(1.4142135623730951)

In [75]:
# the same for multi-dimensional array

In [76]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [77]:
n.min()

np.int64(0)

In [78]:
n.max()

np.int64(20)